language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository

jdk: oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew build test